### ISSUE TITLE
tweet-lm.gz

### ISSUE THREAD

**Issue by diegoceccarelli** [gouwsmeister/TextCleanser#1]
I cannot find the tweet-lm file in the repo, could you add it? or explain how it can be generated? thanks

**Comment by gouwsmeister** [comment]
The language models depend on the type of data that you'll be working with, and should be trained using SRI-LM. It is really easy to train a new language model using SRI-LM, and also very fast. If you want to try out the tool, you can use these two language models that I trained on LA Times English and a sample of tweets that I was working with:

i) https://dl.dropboxusercontent.com/u/2424861/latimes-lm.gz
ii) https://dl.dropboxusercontent.com/u/2424861/tweet-lm.gz

**Comment by phavanh** [comment]
I would like to try out your system, so do you mind if i ask you to share your two language models again. A heap of thanks

**Comment by gouwsmeister** [comment]
I uploaded these two files. latimes-lm.gz is split into two files to come in below the 50Mb limit. Simply join them using cat latimes-lm.gz.part\* > latimes-lm.gz.

**Comment by diegoceccarelli** [comment]
thanks
